rexp/home/urls.py
from django.urls import path, include
from .views import index


app_name = 'home'
urlpatterns = [
    path('', index, name='index'),

]

rexp/rexp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('home.urls', namespace='home')),

]

rexp/user/urls.py
from django.urls import path
from .views import (
    login,
    login_do,
    logout,
    register,
    register_do,
)


app_name = 'user'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('register-do/', register_do, name='register_do'),
    path('login-do/', login_do, name='login_do'),
]

rexp/user/models.py
from django.db import models

# Create your models here.

rexp/core/views.py
from django.shortcuts import render

# Create your views here.

rexp/home/views.py
from django.shortcuts import render
# Create your views here.


def index(request):
    return render(request, 'index.html')

rexp/user/views.py
from django.contrib.auth import login as login_user, authenticate, logout as logout_user
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
from rest_framework.decorators import api_view


def login(request):
    return render(request, 'login.html', status=200)


def register(request):
    return render(request, 'register.html')


def logout(request):
    logout_user(request)
    return redirect('/')


@api_view(['POST'])
def login_do(request):
    status = False
    status_code = 500
    error = ''
    data = []

    try:
        post_data = request.data
        username = post_data.get('username', None)
        password = post_data.get('password', None)
        # Ensure required fields are not empty and expected length
        assert username and len(username) > 3, "Username must be 4 or more characters"
        assert password and len(password) > 6, "Password must be 7 or more characters"
        username = username.lower()
        # Ensure user object exists with given username
        assert User.objects.filter(username=username).exists(), 'No account with given username.'

        # Validate credentials
        user = authenticate(request, username=username, password=password)
        assert user, "Wrong Credentials"
        # Login User
        login_user(request=request, user=user)
        status = True
        status_code = 200
        error = ''
        data = dict()

    except AssertionError as ae:
        status_code = 400
        status = False
        error = str(ae)
        data = {}
    except Exception as e:
        status = False
        status_code = 500
        error = 'Something went wrong'
        data = {}

    return_data = {
        'status': status,
        'error': error,
        'data': data
    }
    return JsonResponse(data=return_data, status=status_code)


@api_view(['POST'])
def register_do(request):
    status = False
    status_code = 500
    error = None
    data = dict()

    try:
        post_data = request.data
        username = post_data.get('username', None)
        password = post_data.get('password', None)
        # Validate fields
        assert username and len(username) > 3, "Username must be at least 4 characters."
        assert password and len(password) > 5, "Password must be at least 6 characters."
        # Assert unique username
        username = username.lower()
        assert not User.objects.filter(username=username).exists(), "This username is taken."
        # Move forward with new entry
        user = User.objects.create(username=username)
        user.set_password(password)
        user.save()
        # authenticate user
        auth_user = authenticate(request, username=username, password=password)
        assert auth_user, "Unable to authenticate your new account."
        # Login user
        login_user(request, auth_user)
        status = True
        error = None
        status_code = 201
        data = {}
    except AssertionError as ae:
        status = False
        error = str(ae)
        data = {}
        status_code = 400

    except Exception as e:
        import traceback
        traceback.print_exc()
        status = False
        status_code = 500
        error = 'Something went wrong.'
        data = {}

    response_data = {
        'status': status,
        'error': error,
        'data': data
    }
    return JsonResponse(data=response_data, status=status_code)

rexp/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <!--<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">-->
    <link rel="stylesheet" href="/static/semantic-ui/semantic.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>-->
    <script src="/static/semantic-ui/semantic.js"></script>
</head>
<body>
<div class="ui container">
    <header>
        <div class="ui secondary  menu">
            <a class="active item">
                Home
            </a>
            <a class="item">
                Messages
            </a>
            <a class="item">
                Friends
            </a>
            <div class="right menu">
                <div class="item">
                    <div class="ui icon input">
                        <input type="text" placeholder="Search...">
                        <i class="search link icon"></i>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                    <a class="ui item" href="javascript:void(0)">
                        {{request.user.username|title}}
                    </a>

                    <a class="ui item" href="{% url 'user:logout' %}">
                        Logout
                    </a>
                {% else %}
                    <a class="ui item" href="{% url 'user:register' %}">
                        Register
                    </a>
                    <a class="ui item" href="{% url 'user:login' %}">
                        Login
                    </a>

                {% endif %}


            </div>
        </div>
    </header>

    <div class="ui basic segment">
        {% block content %}
        {% endblock %}
    </div>

</div>
<script src="/static/dist/commons.js"></script>
</body>
</html>

rexp/home/templates/index.html
{% extends 'base.html'  %}
{% block content %}
<div id="root"></div>
<script src="/static/dist/home/index.js"></script>
{% endblock %}

rexp/user/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div id="login-user" is-user-logged-in="{{ request.user.is_authenticated|yesno:" 1,0,0" }}"></div>
<script src="/static/dist/user/login.js"></script>
{% endblock %}

rexp/user/templates/register.html
{% extends 'base.html' %}
{% block content %}

<div id="register-user" is-user-logged-in="{{ request.user.is_authenticated|yesno:"1,0,0" }}"
    user-register-url="{% url 'user:register_do'%}"
></div>
<script src="/static/dist/user/register.js"></script>
{% endblock %}